
package org.jalgo.tests.ebnf.ebnfinput.GUIPanel;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;

import org.jalgo.module.ebnf.gui.ebnf.ChoicePanel;
import org.jalgo.module.ebnf.gui.ebnf.HeaderViewPanel;
import org.jalgo.module.ebnf.gui.ebnf.InputPanel;
import org.jalgo.module.ebnf.gui.ebnf.RuleViewPanel;

public class GuiPanel extends JPanel {
    
	private static final long serialVersionUID = -5877808882853415899L;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane definitionHeaderViewScrollPanel;
    private javax.swing.JScrollPane definitionRulesViewScrollPanel;
    private javax.swing.JSplitPane definitionViewPanel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    
    public ChoicePanel choicePanel;
    public RuleViewPanel ruleViewPanel;
    public HeaderViewPanel headerViewPanel;
    public InputPanel inputPanel;
    
	/** Creates new form GuiPanel */
    public GuiPanel() {
    	
    	
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mainPanel = new javax.swing.JPanel();
        definitionViewPanel = new JSplitPane();
        definitionHeaderViewScrollPanel = new JScrollPane();
        definitionRulesViewScrollPanel = new JScrollPane();

        definitionViewPanel.setDividerLocation(100);
        definitionViewPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        definitionHeaderViewScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        definitionHeaderViewScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        
        definitionViewPanel.setTopComponent(definitionHeaderViewScrollPanel);
        definitionViewPanel.setBottomComponent(definitionRulesViewScrollPanel);

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(inputPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(definitionViewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                //.add(235, 235, 235)
        		.add(inputPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(definitionViewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 795, Short.MAX_VALUE)
            .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 628, Short.MAX_VALUE)
            .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        
        definitionHeaderViewScrollPanel.setViewportView(headerViewPanel);
        definitionRulesViewScrollPanel.setViewportView(ruleViewPanel);
    }// </editor-fold>//GEN-END:initComponents
    
    
}
