
package org.jalgo.tests.ebnf.ebnfinput.InputPanel;

import javax.swing.JFrame;

public class InputPanel extends JFrame {
    
    /** Creates new form Find */
    public InputPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        InputPanel = new javax.swing.JPanel();
        variableSymbolPanel = new javax.swing.JPanel();
        addVariableButton4 = new javax.swing.JButton();
        addVariableTextField4 = new javax.swing.JTextField();
        StartvariableLabel4 = new javax.swing.JLabel();
        startVariableComboBox4 = new javax.swing.JComboBox();
        terminalSymbolPanel = new javax.swing.JPanel();
        addTerminalButton5 = new javax.swing.JButton();
        addTerminalTextField5 = new javax.swing.JTextField();
        rulePanel = new javax.swing.JPanel();
        addParenthLeftButton5 = new javax.swing.JButton();
        addParenthRightButton5 = new javax.swing.JButton();
        addBarButton5 = new javax.swing.JButton();
        addBraceLeftButton5 = new javax.swing.JButton();
        addBraceRightButton5 = new javax.swing.JButton();
        addBracketLeftButton5 = new javax.swing.JButton();
        addBracketRightButton5 = new javax.swing.JButton();
        addRuleLeftSideComboBox5 = new javax.swing.JComboBox();
        addRuleAssignSymbolLabel5 = new javax.swing.JLabel();
        addRuleRightSideTextbox5 = new javax.swing.JTextField();
        addRuleButton5 = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        checkDefinitionButton5 = new javax.swing.JButton();
        finishInputButton5 = new javax.swing.JButton();

        variableSymbolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Variablensymbole", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        addVariableButton4.setFont(new java.awt.Font("Tahoma", 0, 16));
        addVariableButton4.setText("Hinzuf\u00fcgen");
        addVariableButton4.setMargin(new java.awt.Insets(2, 4, 2, 4));

        addVariableTextField4.setFont(new java.awt.Font("Tahoma", 0, 14));

        StartvariableLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        StartvariableLabel4.setText("Startvariable:");

        startVariableComboBox4.setFont(new java.awt.Font("Tahoma", 0, 12));
        startVariableComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<SimpleExpression>" }));

        org.jdesktop.layout.GroupLayout variableSymbolPanelLayout = new org.jdesktop.layout.GroupLayout(variableSymbolPanel);
        variableSymbolPanel.setLayout(variableSymbolPanelLayout);
        variableSymbolPanelLayout.setHorizontalGroup(
            variableSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, variableSymbolPanelLayout.createSequentialGroup()
                .add(addVariableTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addVariableButton4))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, variableSymbolPanelLayout.createSequentialGroup()
                .add(StartvariableLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(startVariableComboBox4, 0, 130, Short.MAX_VALUE))
        );
        variableSymbolPanelLayout.setVerticalGroup(
            variableSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(variableSymbolPanelLayout.createSequentialGroup()
                .add(variableSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addVariableButton4)
                    .add(addVariableTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(variableSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(StartvariableLabel4)
                    .add(startVariableComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        terminalSymbolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terminalsymbole", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        terminalSymbolPanel.setMinimumSize(new java.awt.Dimension(22, 36));
        addTerminalButton5.setFont(new java.awt.Font("Tahoma", 0, 16));
        addTerminalButton5.setText("Hinzuf\u00fcgen");
        addTerminalButton5.setMargin(new java.awt.Insets(2, 4, 2, 4));

        addTerminalTextField5.setFont(new java.awt.Font("Tahoma", 0, 14));

        org.jdesktop.layout.GroupLayout terminalSymbolPanelLayout = new org.jdesktop.layout.GroupLayout(terminalSymbolPanel);
        terminalSymbolPanel.setLayout(terminalSymbolPanelLayout);
        terminalSymbolPanelLayout.setHorizontalGroup(
            terminalSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, terminalSymbolPanelLayout.createSequentialGroup()
                .add(addTerminalTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addTerminalButton5))
        );
        terminalSymbolPanelLayout.setVerticalGroup(
            terminalSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(terminalSymbolPanelLayout.createSequentialGroup()
                .add(terminalSymbolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addTerminalButton5)
                    .add(addTerminalTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        rulePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Regeln", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        addParenthLeftButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addParenthLeftButton5.setText("(");
        addParenthLeftButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addParenthRightButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addParenthRightButton5.setText(")");
        addParenthRightButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addBarButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addBarButton5.setText("|");
        addBarButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addBraceLeftButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addBraceLeftButton5.setText("{");
        addBraceLeftButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addBraceRightButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addBraceRightButton5.setText("}");
        addBraceRightButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addBracketLeftButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addBracketLeftButton5.setText("[");
        addBracketLeftButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addBracketRightButton5.setFont(new java.awt.Font("Tahoma", 0, 20));
        addBracketRightButton5.setText("]");
        addBracketRightButton5.setMargin(new java.awt.Insets(3, 5, 2, 5));

        addRuleLeftSideComboBox5.setFont(new java.awt.Font("Tahoma", 0, 16));
        addRuleLeftSideComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<SimpleExpression>" }));

        addRuleAssignSymbolLabel5.setFont(new java.awt.Font("Tahoma", 1, 16));
        addRuleAssignSymbolLabel5.setText("::=");

        addRuleRightSideTextbox5.setFont(new java.awt.Font("Tahoma", 0, 18));

        addRuleButton5.setFont(new java.awt.Font("Tahoma", 0, 16));
        addRuleButton5.setText("Hinzuf\u00fcgen");
        addRuleButton5.setMargin(new java.awt.Insets(2, 4, 2, 4));

        org.jdesktop.layout.GroupLayout rulePanelLayout = new org.jdesktop.layout.GroupLayout(rulePanel);
        rulePanel.setLayout(rulePanelLayout);
        rulePanelLayout.setHorizontalGroup(
            rulePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(addRuleLeftSideComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addRuleAssignSymbolLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rulePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rulePanelLayout.createSequentialGroup()
                        .add(addParenthLeftButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addBarButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addParenthRightButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addBraceLeftButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addBraceRightButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addBracketLeftButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addBracketRightButton5)
                        .addContainerGap())
                    .add(rulePanelLayout.createSequentialGroup()
                        .add(addRuleRightSideTextbox5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addRuleButton5)
                        .add(0, 0, 0))))
        );
        rulePanelLayout.setVerticalGroup(
            rulePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rulePanelLayout.createSequentialGroup()
                .add(rulePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addBarButton5)
                    .add(addParenthRightButton5)
                    .add(addBraceLeftButton5)
                    .add(addBraceRightButton5)
                    .add(addBracketLeftButton5)
                    .add(addBracketRightButton5)
                    .add(addParenthLeftButton5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rulePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rulePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(addRuleRightSideTextbox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(addRuleAssignSymbolLabel5)
                        .add(addRuleButton5))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, addRuleLeftSideComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Weiter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        checkDefinitionButton5.setFont(new java.awt.Font("Tahoma", 0, 14));
        checkDefinitionButton5.setText("<html><center>Defintion<br>pr\u00fcfenn</center></html>");

        finishInputButton5.setFont(new java.awt.Font("Tahoma", 1, 14));
        finishInputButton5.setText("<html><center>Eingabe<br>beenden</center></html>");

        org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(checkDefinitionButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
            .add(finishInputButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .add(checkDefinitionButton5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(finishInputButton5))
        );

        org.jdesktop.layout.GroupLayout InputPanelLayout = new org.jdesktop.layout.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(InputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, InputPanelLayout.createSequentialGroup()
                        .add(variableSymbolPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(terminalSymbolPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(rulePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InputPanelLayout.linkSize(new java.awt.Component[] {terminalSymbolPanel, variableSymbolPanel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(InputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(buttonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, InputPanelLayout.createSequentialGroup()
                        .add(InputPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(variableSymbolPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(terminalSymbolPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(rulePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        InputPanelLayout.linkSize(new java.awt.Component[] {rulePanel, terminalSymbolPanel, variableSymbolPanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(InputPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(InputPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputPanel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel StartvariableLabel4;
    private javax.swing.JButton addBarButton5;
    private javax.swing.JButton addBraceLeftButton5;
    private javax.swing.JButton addBraceRightButton5;
    private javax.swing.JButton addBracketLeftButton5;
    private javax.swing.JButton addBracketRightButton5;
    private javax.swing.JButton addParenthLeftButton5;
    private javax.swing.JButton addParenthRightButton5;
    private javax.swing.JLabel addRuleAssignSymbolLabel5;
    private javax.swing.JButton addRuleButton5;
    private javax.swing.JComboBox addRuleLeftSideComboBox5;
    private javax.swing.JTextField addRuleRightSideTextbox5;
    private javax.swing.JButton addTerminalButton5;
    private javax.swing.JTextField addTerminalTextField5;
    private javax.swing.JButton addVariableButton4;
    private javax.swing.JTextField addVariableTextField4;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton checkDefinitionButton5;
    private javax.swing.JButton finishInputButton5;
    private javax.swing.JPanel rulePanel;
    private javax.swing.JComboBox startVariableComboBox4;
    private javax.swing.JPanel terminalSymbolPanel;
    private javax.swing.JPanel variableSymbolPanel;
    // End of variables declaration//GEN-END:variables
    
}
