
package org.jalgo.tests.ebnf.ebnfinput.RuleViewPanel;

import javax.swing.JPanel;

public class RuleViewPanel extends JPanel {
    
    /** Creates new form RuleViewPanel */
    public RuleViewPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        RuleViewPanel = new javax.swing.JPanel();
        ruleLabel1 = new javax.swing.JLabel();
        ruleLabel2 = new javax.swing.JLabel();
        ruleLabel3 = new javax.swing.JLabel();
        ruleLabel5 = new javax.swing.JLabel();
        ruleLabel6 = new javax.swing.JLabel();
        ruleLabel7 = new javax.swing.JLabel();

        RuleViewPanel.setBackground(new java.awt.Color(255, 255, 255));
        ruleLabel1.setFont(new java.awt.Font("Tahoma", 0, 16));
        ruleLabel1.setText("::= [+|-] <Term> {(+|-)<Term>}");

        ruleLabel2.setFont(new java.awt.Font("Tahoma", 0, 16));
        ruleLabel2.setText("::= <Factor> {(*|/|%)<Factor>}");

        ruleLabel3.setFont(new java.awt.Font("Tahoma", 0, 16));
        ruleLabel3.setText("<Factor>");

        ruleLabel5.setFont(new java.awt.Font("Tahoma", 0, 16));
        ruleLabel5.setText("::= <Ident>|<Number>|(<SimpleExpression>)");

        ruleLabel6.setFont(new java.awt.Font("Tahoma", 0, 16));
        ruleLabel6.setText("<Term>");

        ruleLabel7.setFont(new java.awt.Font("Tahoma", 0, 16));
        ruleLabel7.setText("<SimpleExpression>");

        org.jdesktop.layout.GroupLayout RuleViewPanelLayout = new org.jdesktop.layout.GroupLayout(RuleViewPanel);
        RuleViewPanel.setLayout(RuleViewPanelLayout);
        RuleViewPanelLayout.setHorizontalGroup(
            RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RuleViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(ruleLabel3)
                    .add(ruleLabel6)
                    .add(ruleLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ruleLabel1)
                    .add(ruleLabel2)
                    .add(ruleLabel5))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        RuleViewPanelLayout.setVerticalGroup(
            RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RuleViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ruleLabel1)
                    .add(ruleLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ruleLabel2)
                    .add(ruleLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RuleViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ruleLabel3)
                    .add(ruleLabel5))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RuleViewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RuleViewPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RuleViewPanel;
    private javax.swing.JLabel ruleLabel1;
    private javax.swing.JLabel ruleLabel2;
    private javax.swing.JLabel ruleLabel3;
    private javax.swing.JLabel ruleLabel5;
    private javax.swing.JLabel ruleLabel6;
    private javax.swing.JLabel ruleLabel7;
    // End of variables declaration//GEN-END:variables
    
}
