/* Generated By:JavaCC: Do not edit this line. EbnfParserConstants.java */
package org.jalgo.module.ebnf.controller.ebnf.parser;

public interface EbnfParserConstants {

  int EOF = 0;
  int L_REPETITION = 5;
  int R_REPETITION = 6;
  int L_PARENTHESES = 7;
  int R_PARENTHESES = 8;
  int L_OPTION = 9;
  int R_OPTION = 10;
  int BRANCH = 11;
  int TERM = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\u300f\"",
    "\"\\u3010\"",
    "\"\\u3011\"",
    "\"\\u3012\"",
    "\"\\u300c\"",
    "\"\\u300d\"",
    "\"\\u300e\"",
    "<TERM>",
  };

}
