/*
 * j-Algo - j-Algo is an algorithm visualization tool, especially useful for
 * students and lecturers of computer science. It is written in Java and platform
 * independent. j-Algo is developed with the help of Dresden University of
 * Technology.
 * 
 * Copyright (C) 2004-2010 j-Algo-Team, j-algo-development@lists.sourceforge.net
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA 02111-1307 USA
 */
/* The following code was generated by JFlex 1.4.3 on 30.06.10 19:59 */

/* WARNING: This is generated code. DO *NOT* MODIFY IT! */
package org.jalgo.module.am0c0.parser.c0;

import beaver.Symbol;
import beaver.Scanner;
import org.jalgo.module.am0c0.parser.ParserConstants;
import org.jalgo.module.am0c0.parser.c0.GeneratedC0Parser.Terminals;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30.06.10 19:59 from the specification file
 * <tt>/home/mm/Projekte/SWP/module/c0-lexer.l</tt>
 */
class C0Scanner extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\3\1\1\1\1\1\0\1\1\1\1\16\3\4\0\1\1\1\51"+
    "\1\45\1\10\1\2\1\46\1\40\1\0\1\31\1\32\1\7\1\47"+
    "\1\36\1\50\1\24\1\6\1\4\11\5\1\0\1\37\1\20\1\35"+
    "\1\26\2\0\32\2\4\0\1\2\1\0\1\30\1\2\1\13\1\16"+
    "\1\17\1\41\1\2\1\25\1\11\2\2\1\14\1\27\1\12\1\23"+
    "\1\43\1\2\1\44\1\21\1\22\1\15\1\2\1\42\3\2\1\33"+
    "\1\0\1\34\1\0\41\3\2\0\4\2\4\0\1\2\2\0\1\3"+
    "\7\0\1\2\4\0\1\2\5\0\27\2\1\0\37\2\1\0\u013f\2"+
    "\31\0\162\2\4\0\14\2\16\0\5\2\11\0\1\2\21\0\130\3"+
    "\5\0\23\3\12\0\1\2\13\0\1\2\1\0\3\2\1\0\1\2"+
    "\1\0\24\2\1\0\54\2\1\0\46\2\1\0\5\2\4\0\202\2"+
    "\1\0\4\3\3\0\105\2\1\0\46\2\2\0\2\2\6\0\20\2"+
    "\41\0\46\2\2\0\1\2\7\0\47\2\11\0\21\3\1\0\27\3"+
    "\1\0\3\3\1\0\1\3\1\0\2\3\1\0\1\3\13\0\33\2"+
    "\5\0\3\2\15\0\4\3\14\0\6\3\13\0\32\2\5\0\13\2"+
    "\16\3\7\0\12\3\4\0\2\2\1\3\143\2\1\0\1\2\10\3"+
    "\1\0\6\3\2\2\2\3\1\0\4\3\2\2\12\3\3\2\2\0"+
    "\1\2\17\0\1\3\1\2\1\3\36\2\33\3\2\0\3\2\60\0"+
    "\46\2\13\3\1\2\u014f\0\3\3\66\2\2\0\1\3\1\2\20\3"+
    "\2\0\1\2\4\3\3\0\12\2\2\3\2\0\12\3\21\0\3\3"+
    "\1\0\10\2\2\0\2\2\2\0\26\2\1\0\7\2\1\0\1\2"+
    "\3\0\4\2\2\0\1\3\1\2\7\3\2\0\2\3\2\0\3\3"+
    "\11\0\1\3\4\0\2\2\1\0\3\2\2\3\2\0\12\3\4\2"+
    "\15\0\3\3\1\0\6\2\4\0\2\2\2\0\26\2\1\0\7\2"+
    "\1\0\2\2\1\0\2\2\1\0\2\2\2\0\1\3\1\0\5\3"+
    "\4\0\2\3\2\0\3\3\13\0\4\2\1\0\1\2\7\0\14\3"+
    "\3\2\14\0\3\3\1\0\11\2\1\0\3\2\1\0\26\2\1\0"+
    "\7\2\1\0\2\2\1\0\5\2\2\0\1\3\1\2\10\3\1\0"+
    "\3\3\1\0\3\3\2\0\1\2\17\0\2\2\2\3\2\0\12\3"+
    "\1\0\1\2\17\0\3\3\1\0\10\2\2\0\2\2\2\0\26\2"+
    "\1\0\7\2\1\0\2\2\1\0\5\2\2\0\1\3\1\2\6\3"+
    "\3\0\2\3\2\0\3\3\10\0\2\3\4\0\2\2\1\0\3\2"+
    "\4\0\12\3\1\0\1\2\20\0\1\3\1\2\1\0\6\2\3\0"+
    "\3\2\1\0\4\2\3\0\2\2\1\0\1\2\1\0\2\2\3\0"+
    "\2\2\3\0\3\2\3\0\10\2\1\0\3\2\4\0\5\3\3\0"+
    "\3\3\1\0\4\3\11\0\1\3\17\0\11\3\11\0\1\2\7\0"+
    "\3\3\1\0\10\2\1\0\3\2\1\0\27\2\1\0\12\2\1\0"+
    "\5\2\4\0\7\3\1\0\3\3\1\0\4\3\7\0\2\3\11\0"+
    "\2\2\4\0\12\3\22\0\2\3\1\0\10\2\1\0\3\2\1\0"+
    "\27\2\1\0\12\2\1\0\5\2\2\0\1\3\1\2\7\3\1\0"+
    "\3\3\1\0\4\3\7\0\2\3\7\0\1\2\1\0\2\2\4\0"+
    "\12\3\22\0\2\3\1\0\10\2\1\0\3\2\1\0\27\2\1\0"+
    "\20\2\4\0\6\3\2\0\3\3\1\0\4\3\11\0\1\3\10\0"+
    "\2\2\4\0\12\3\22\0\2\3\1\0\22\2\3\0\30\2\1\0"+
    "\11\2\1\0\1\2\2\0\7\2\3\0\1\3\4\0\6\3\1\0"+
    "\1\3\1\0\10\3\22\0\2\3\15\0\60\2\1\3\2\2\7\3"+
    "\4\0\10\2\10\3\1\0\12\3\47\0\2\2\1\0\1\2\2\0"+
    "\2\2\1\0\1\2\2\0\1\2\6\0\4\2\1\0\7\2\1\0"+
    "\3\2\1\0\1\2\1\0\1\2\2\0\2\2\1\0\4\2\1\3"+
    "\2\2\6\3\1\0\2\3\1\2\2\0\5\2\1\0\1\2\1\0"+
    "\6\3\2\0\12\3\2\0\2\2\42\0\1\2\27\0\2\3\6\0"+
    "\12\3\13\0\1\3\1\0\1\3\1\0\1\3\4\0\2\3\10\2"+
    "\1\0\42\2\6\0\24\3\1\0\2\3\4\2\4\0\10\3\1\0"+
    "\44\3\11\0\1\3\71\0\42\2\1\0\5\2\1\0\2\2\1\0"+
    "\7\3\3\0\4\3\6\0\12\3\6\0\6\2\4\3\106\0\46\2"+
    "\12\0\51\2\7\0\132\2\5\0\104\2\5\0\122\2\6\0\7\2"+
    "\1\0\77\2\1\0\1\2\1\0\4\2\2\0\7\2\1\0\1\2"+
    "\1\0\4\2\2\0\47\2\1\0\1\2\1\0\4\2\2\0\37\2"+
    "\1\0\1\2\1\0\4\2\2\0\7\2\1\0\1\2\1\0\4\2"+
    "\2\0\7\2\1\0\7\2\1\0\27\2\1\0\37\2\1\0\1\2"+
    "\1\0\4\2\2\0\7\2\1\0\47\2\1\0\23\2\16\0\11\3"+
    "\56\0\125\2\14\0\u026c\2\2\0\10\2\12\0\32\2\5\0\113\2"+
    "\3\0\3\2\17\0\15\2\1\0\4\2\3\3\13\0\22\2\3\3"+
    "\13\0\22\2\2\3\14\0\15\2\1\0\3\2\1\0\2\3\14\0"+
    "\64\2\40\3\3\0\1\2\3\0\2\2\1\3\2\0\12\3\41\0"+
    "\3\3\2\0\12\3\6\0\130\2\10\0\51\2\1\3\126\0\35\2"+
    "\3\0\14\3\4\0\14\3\12\0\12\3\36\2\2\0\5\2\u038b\0"+
    "\154\2\224\0\234\2\4\0\132\2\6\0\26\2\2\0\6\2\2\0"+
    "\46\2\2\0\6\2\2\0\10\2\1\0\1\2\1\0\1\2\1\0"+
    "\1\2\1\0\37\2\2\0\65\2\1\0\7\2\1\0\1\2\3\0"+
    "\3\2\1\0\7\2\3\0\4\2\2\0\6\2\4\0\15\2\5\0"+
    "\3\2\1\0\7\2\17\0\4\3\32\0\5\3\20\0\2\2\23\0"+
    "\1\2\13\0\4\3\6\0\6\3\1\0\1\2\15\0\1\2\40\0"+
    "\22\2\36\0\15\3\4\0\1\3\3\0\6\3\27\0\1\2\4\0"+
    "\1\2\2\0\12\2\1\0\1\2\3\0\5\2\6\0\1\2\1\0"+
    "\1\2\1\0\1\2\1\0\4\2\1\0\3\2\1\0\7\2\3\0"+
    "\3\2\5\0\5\2\26\0\44\2\u0e81\0\3\2\31\0\11\2\6\3"+
    "\1\0\5\2\2\0\5\2\4\0\126\2\2\0\2\3\2\0\3\2"+
    "\1\0\137\2\5\0\50\2\4\0\136\2\21\0\30\2\70\0\20\2"+
    "\u0200\0\u19b6\2\112\0\u51a6\2\132\0\u048d\2\u0773\0\u2ba4\2\u215c\0\u012e\2"+
    "\2\0\73\2\225\0\7\2\14\0\5\2\5\0\1\2\1\3\12\2"+
    "\1\0\15\2\1\0\5\2\1\0\1\2\1\0\2\2\1\0\2\2"+
    "\1\0\154\2\41\0\u016b\2\22\0\100\2\2\0\66\2\50\0\15\2"+
    "\3\0\20\3\20\0\4\3\17\0\2\2\30\0\3\2\31\0\1\2"+
    "\6\0\5\2\1\0\207\2\2\0\1\3\4\0\1\2\13\0\12\3"+
    "\7\0\32\2\4\0\1\2\1\0\32\2\12\0\132\2\3\0\6\2"+
    "\2\0\6\2\2\0\6\2\2\0\3\2\3\0\2\2\3\0\2\2"+
    "\22\0\3\3\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\5\1\6\1\1"+
    "\3\3\1\7\1\3\1\10\1\3\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\3\3\1\1\1\21"+
    "\1\22\1\23\1\1\2\0\1\3\1\24\2\3\1\0"+
    "\1\25\1\3\1\26\1\3\1\27\3\3\1\0\1\30"+
    "\3\0\1\31\2\3\1\0\5\3\3\0\1\2\1\0"+
    "\1\3\1\32\1\0\1\3\1\33\3\3\1\34\1\35"+
    "\1\0\1\36\1\0\1\37\1\40\2\3\2\0\1\41"+
    "\1\3\3\0\1\42\1\0\1\43\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\52\0\250\0\322\0\52"+
    "\0\374\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222"+
    "\0\52\0\52\0\52\0\52\0\u024c\0\52\0\52\0\52"+
    "\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\52\0\52\0\52\0\u031e"+
    "\0\u0348\0\u0372\0\u039c\0\176\0\u03c6\0\u03f0\0\u041a\0\52"+
    "\0\u0444\0\52\0\u046e\0\52\0\u0498\0\u04c2\0\u04ec\0\u0516"+
    "\0\52\0\u0540\0\u056a\0\u0594\0\176\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738\0\u0762"+
    "\0\52\0\u078c\0\u07b6\0\176\0\u07e0\0\u080a\0\176\0\u0834"+
    "\0\u085e\0\u0888\0\52\0\52\0\u08b2\0\176\0\u08dc\0\176"+
    "\0\176\0\u0906\0\u0930\0\u095a\0\u0984\0\176\0\u09ae\0\u09d8"+
    "\0\u0a02\0\u0a2c\0\52\0\u0a56\0\52\0\52";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\4\1\13\3\4\1\14\1\15\1\16"+
    "\2\4\1\2\1\4\1\17\1\20\1\4\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\4\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\53\0"+
    "\1\3\52\0\4\4\3\0\7\4\1\0\3\4\1\0"+
    "\1\4\1\0\2\4\10\0\4\4\11\0\2\6\53\0"+
    "\1\41\53\0\1\42\42\0\4\4\3\0\1\4\1\43"+
    "\5\4\1\0\3\4\1\0\1\4\1\0\2\4\10\0"+
    "\1\44\3\4\7\0\4\4\3\0\7\4\1\0\2\4"+
    "\1\45\1\0\1\4\1\0\2\4\10\0\4\4\7\0"+
    "\4\4\3\0\3\4\1\46\3\4\1\0\3\4\1\0"+
    "\1\4\1\0\2\4\10\0\4\4\26\0\1\47\13\0"+
    "\1\50\16\0\4\4\3\0\2\4\1\51\4\4\1\0"+
    "\3\4\1\0\1\4\1\0\2\4\10\0\4\4\42\0"+
    "\1\52\16\0\4\4\3\0\7\4\1\0\3\4\1\0"+
    "\1\4\1\0\1\4\1\53\10\0\4\4\42\0\1\54"+
    "\16\0\4\4\3\0\7\4\1\0\3\4\1\0\1\55"+
    "\1\0\2\4\10\0\4\4\7\0\4\4\3\0\7\4"+
    "\1\0\3\4\1\0\1\4\1\0\2\4\10\0\3\4"+
    "\1\56\7\0\4\4\3\0\6\4\1\57\1\0\3\4"+
    "\1\0\1\4\1\0\2\4\10\0\4\4\53\0\1\60"+
    "\40\0\1\61\14\0\7\62\1\63\42\62\12\0\1\64"+
    "\41\0\4\4\3\0\7\4\1\0\1\4\1\65\1\4"+
    "\1\0\1\4\1\0\2\4\10\0\4\4\7\0\4\4"+
    "\3\0\1\4\1\66\5\4\1\0\3\4\1\0\1\4"+
    "\1\0\2\4\10\0\4\4\7\0\4\4\3\0\7\4"+
    "\1\0\1\67\2\4\1\0\1\4\1\0\2\4\10\0"+
    "\4\4\27\0\1\70\31\0\4\4\3\0\7\4\1\0"+
    "\3\4\1\0\1\4\1\0\1\4\1\71\10\0\4\4"+
    "\7\0\4\4\3\0\1\72\6\4\1\0\3\4\1\0"+
    "\1\4\1\0\2\4\10\0\4\4\7\0\4\4\3\0"+
    "\1\73\6\4\1\0\3\4\1\0\1\4\1\0\2\4"+
    "\10\0\4\4\7\0\4\4\3\0\1\74\6\4\1\0"+
    "\3\4\1\0\1\4\1\0\2\4\10\0\4\4\7\0"+
    "\4\4\3\0\7\4\1\0\1\4\1\75\1\4\1\0"+
    "\1\4\1\0\2\4\10\0\4\4\16\0\1\76\4\0"+
    "\1\77\33\0\7\62\1\100\42\62\6\0\1\101\1\63"+
    "\55\0\1\102\40\0\4\4\3\0\7\4\1\0\1\103"+
    "\2\4\1\0\1\4\1\0\2\4\10\0\4\4\7\0"+
    "\4\4\3\0\6\4\1\104\1\0\3\4\1\0\1\4"+
    "\1\0\2\4\10\0\4\4\23\0\1\105\35\0\4\4"+
    "\3\0\1\4\1\106\5\4\1\0\3\4\1\0\1\4"+
    "\1\0\2\4\10\0\4\4\7\0\4\4\3\0\1\4"+
    "\1\107\5\4\1\0\3\4\1\0\1\4\1\0\2\4"+
    "\10\0\4\4\7\0\4\4\3\0\3\4\1\110\3\4"+
    "\1\0\3\4\1\0\1\4\1\0\2\4\10\0\4\4"+
    "\7\0\4\4\3\0\1\4\1\111\5\4\1\0\3\4"+
    "\1\0\1\4\1\0\2\4\10\0\4\4\7\0\4\4"+
    "\3\0\4\4\1\112\2\4\1\0\3\4\1\0\1\4"+
    "\1\0\2\4\10\0\4\4\52\0\1\113\51\0\1\114"+
    "\4\0\6\62\1\101\1\100\42\62\14\0\1\115\37\0"+
    "\4\4\3\0\7\4\1\0\1\4\1\116\1\4\1\0"+
    "\1\4\1\0\2\4\10\0\4\4\16\0\1\117\42\0"+
    "\4\4\3\0\7\4\1\0\3\4\1\0\1\4\1\0"+
    "\2\4\10\0\1\120\3\4\7\0\4\4\3\0\6\4"+
    "\1\121\1\0\3\4\1\0\1\4\1\0\2\4\10\0"+
    "\4\4\7\0\4\4\3\0\7\4\1\0\1\4\1\122"+
    "\1\4\1\0\1\4\1\0\2\4\10\0\4\4\7\0"+
    "\4\4\3\0\7\4\1\0\3\4\1\0\1\4\1\0"+
    "\2\4\10\0\3\4\1\123\22\0\1\124\57\0\1\125"+
    "\30\0\4\4\3\0\7\4\1\0\3\4\1\0\1\4"+
    "\1\0\2\4\10\0\1\126\3\4\7\0\4\4\3\0"+
    "\1\4\1\127\5\4\1\0\3\4\1\0\1\4\1\0"+
    "\2\4\10\0\4\4\23\0\1\130\57\0\1\131\26\0"+
    "\1\132\4\4\3\0\7\4\1\0\3\4\1\0\1\4"+
    "\1\0\2\4\10\0\4\4\24\0\1\133\57\0\1\134"+
    "\25\0\1\132\2\0\1\135\73\0\1\136\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2688];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\1\11\10\1\4\11"+
    "\1\1\3\11\4\1\3\11\1\1\2\0\4\1\1\0"+
    "\1\11\1\1\1\11\1\1\1\11\3\1\1\0\1\11"+
    "\3\0\3\1\1\0\5\1\3\0\1\11\1\0\2\1"+
    "\1\0\5\1\2\11\1\0\1\1\1\0\4\1\2\0"+
    "\2\1\3\0\1\11\1\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(short id, Object value)
    {
        return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  C0Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  C0Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1746) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { /* ignore */
          }
        case 37: break;
        case 36: 
          { return symbol(Terminals.STDIO, "<stdio.h>");
          }
        case 38: break;
        case 16: 
          { return symbol(Terminals.AMP, "&");
          }
        case 39: break;
        case 34: 
          { return symbol(Terminals.INCLUDE, "#include");
          }
        case 40: break;
        case 26: 
          { return symbol(Terminals.ELSE, "else");
          }
        case 41: break;
        case 18: 
          { return symbol(Terminals.PLUS, "+");
          }
        case 42: break;
        case 4: 
          { return symbol(Terminals.NUMBER, yytext());
          }
        case 43: break;
        case 12: 
          { return symbol(Terminals.RBRACKET, "}");
          }
        case 44: break;
        case 5: 
          { return symbol(Terminals.DIV, "/");
          }
        case 45: break;
        case 35: 
          { return symbol(Terminals.RETURN, "return 0");
          }
        case 46: break;
        case 28: 
          { return symbol(Terminals.IFORMAT, "\"%i\"");
          }
        case 47: break;
        case 8: 
          { return symbol(Terminals.GT, ">");
          }
        case 48: break;
        case 10: 
          { return symbol(Terminals.RPAREN, ")");
          }
        case 49: break;
        case 24: 
          { return symbol(Terminals.NE, "!=");
          }
        case 50: break;
        case 30: 
          { return symbol(Terminals.CONST, "const");
          }
        case 51: break;
        case 32: 
          { return symbol(Terminals.WHILE, "while");
          }
        case 52: break;
        case 21: 
          { return symbol(Terminals.LE, "<=");
          }
        case 53: break;
        case 6: 
          { return symbol(Terminals.MULT, "*");
          }
        case 54: break;
        case 7: 
          { return symbol(Terminals.LT, "<");
          }
        case 55: break;
        case 27: 
          { return symbol(Terminals.MAIN, "main");
          }
        case 56: break;
        case 9: 
          { return symbol(Terminals.LPAREN, "(");
          }
        case 57: break;
        case 14: 
          { return symbol(Terminals.COMMA, ",");
          }
        case 58: break;
        case 25: 
          { return symbol(Terminals.INT, "int");
          }
        case 59: break;
        case 11: 
          { return symbol(Terminals.LBRACKET, "{");
          }
        case 60: break;
        case 33: 
          { return symbol(Terminals.PRINTF, "printf");
          }
        case 61: break;
        case 29: 
          { return symbol(Terminals.DFORMAT, "\"%d\"");
          }
        case 62: break;
        case 3: 
          { return symbol(Terminals.IDENT, yytext());
          }
        case 63: break;
        case 20: 
          { return symbol(Terminals.IF, "if");
          }
        case 64: break;
        case 19: 
          { return symbol(Terminals.MINUS, "-");
          }
        case 65: break;
        case 23: 
          { return symbol(Terminals.EQ, "==");
          }
        case 66: break;
        case 22: 
          { return symbol(Terminals.GE, ">=");
          }
        case 67: break;
        case 31: 
          { return symbol(Terminals.SCANF, "scanf");
          }
        case 68: break;
        case 15: 
          { return symbol(Terminals.SEMICOLON, ";");
          }
        case 69: break;
        case 13: 
          { return symbol(Terminals.ASSIGN, "=");
          }
        case 70: break;
        case 1: 
          { throw new Scanner.Exception(yyline + 1, yycolumn + 1, yytext());
          }
        case 71: break;
        case 17: 
          { return symbol(Terminals.MOD, "%");
          }
        case 72: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {     return symbol(Terminals.EOF, ParserConstants.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
